package neu.edu.entity;
// Generated Apr 28, 2017 7:49:59 AM by Hibernate Tools 5.2.1.Final

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private Integer id;
	private Projects projects;
	private UserAccounts userAccounts;
	private String comments;

	public Comments() {
	}

	public Comments(Projects projects, UserAccounts userAccounts, String comments) {
		this.projects = projects;
		this.userAccounts = userAccounts;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public UserAccounts getUserAccounts() {
		return this.userAccounts;
	}

	public void setUserAccounts(UserAccounts userAccounts) {
		this.userAccounts = userAccounts;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
