package neu.edu.entity;
// Generated Apr 28, 2017 7:49:59 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projects generated by hbm2java
 */
public class Projects implements java.io.Serializable {

	private Integer id;
	private Category category;
	private UserAccounts userAccounts;
	private String name;
	private String description;
	private Integer requiredFunds;
	private Integer acquiredFunds;
	private Date startDate;
	private Date endDate;
	private Integer donationsAllowed;
	private Integer donationReceived;
	private Byte isActive;
	private Byte isDeleted;
	private Set<Returns> returnses = new HashSet<Returns>(0);
	private Set<Comments> commentses = new HashSet<Comments>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Projects() {
	}

	public Projects(Category category, UserAccounts userAccounts, String name, String description,
			Integer requiredFunds, Integer acquiredFunds, Date startDate, Date endDate, Integer donationsAllowed,
			Integer donationReceived, Byte isActive, Byte isDeleted, Set<Returns> returnses, Set<Comments> commentses,
			Set<Payment> payments) {
		this.category = category;
		this.userAccounts = userAccounts;
		this.name = name;
		this.description = description;
		this.requiredFunds = requiredFunds;
		this.acquiredFunds = acquiredFunds;
		this.startDate = startDate;
		this.endDate = endDate;
		this.donationsAllowed = donationsAllowed;
		this.donationReceived = donationReceived;
		this.isActive = isActive;
		this.isDeleted = isDeleted;
		this.returnses = returnses;
		this.commentses = commentses;
		this.payments = payments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public UserAccounts getUserAccounts() {
		return this.userAccounts;
	}

	public void setUserAccounts(UserAccounts userAccounts) {
		this.userAccounts = userAccounts;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getRequiredFunds() {
		return this.requiredFunds;
	}

	public void setRequiredFunds(Integer requiredFunds) {
		this.requiredFunds = requiredFunds;
	}

	public Integer getAcquiredFunds() {
		return this.acquiredFunds;
	}

	public void setAcquiredFunds(Integer acquiredFunds) {
		this.acquiredFunds = acquiredFunds;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getDonationsAllowed() {
		return this.donationsAllowed;
	}

	public void setDonationsAllowed(Integer donationsAllowed) {
		this.donationsAllowed = donationsAllowed;
	}

	public Integer getDonationReceived() {
		return this.donationReceived;
	}

	public void setDonationReceived(Integer donationReceived) {
		this.donationReceived = donationReceived;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<Returns> getReturnses() {
		return this.returnses;
	}

	public void setReturnses(Set<Returns> returnses) {
		this.returnses = returnses;
	}

	public Set<Comments> getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set<Comments> commentses) {
		this.commentses = commentses;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
