package neu.edu.entity;
// Generated Apr 28, 2017 7:49:59 AM by Hibernate Tools 5.2.1.Final

/**
 * Returns generated by hbm2java
 */
public class Returns implements java.io.Serializable {

	private Integer id;
	private Projects projects;
	private Integer amount;
	private Integer returnNum;
	private String returnDesc;

	public Returns() {
	}

	public Returns(Projects projects, Integer amount, Integer returnNum, String returnDesc) {
		this.projects = projects;
		this.amount = amount;
		this.returnNum = returnNum;
		this.returnDesc = returnDesc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Integer getReturnNum() {
		return this.returnNum;
	}

	public void setReturnNum(Integer returnNum) {
		this.returnNum = returnNum;
	}

	public String getReturnDesc() {
		return this.returnDesc;
	}

	public void setReturnDesc(String returnDesc) {
		this.returnDesc = returnDesc;
	}

}
