package neu.edu.entity;
// Generated Apr 28, 2017 7:49:59 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Integer id;
	private String role;
	private String roleDesc;
	private Set<UserAccounts> userAccountses = new HashSet<UserAccounts>(0);

	public Roles() {
	}

	public Roles(String role, String roleDesc, Set<UserAccounts> userAccountses) {
		this.role = role;
		this.roleDesc = roleDesc;
		this.userAccountses = userAccountses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Set<UserAccounts> getUserAccountses() {
		return this.userAccountses;
	}

	public void setUserAccountses(Set<UserAccounts> userAccountses) {
		this.userAccountses = userAccountses;
	}

}
