package neu.edu.entity;
// Generated Apr 28, 2017 7:49:59 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserPaymentInfo generated by hbm2java
 */
public class UserPaymentInfo implements java.io.Serializable {

	private Integer id;
	private UserAccounts userAccounts;
	private String cardNum;
	private String cardExp;
	private Integer cardCvv;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public UserPaymentInfo() {
	}

	public UserPaymentInfo(UserAccounts userAccounts, String cardNum, String cardExp, Integer cardCvv,
			Set<Payment> payments) {
		this.userAccounts = userAccounts;
		this.cardNum = cardNum;
		this.cardExp = cardExp;
		this.cardCvv = cardCvv;
		this.payments = payments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserAccounts getUserAccounts() {
		return this.userAccounts;
	}

	public void setUserAccounts(UserAccounts userAccounts) {
		this.userAccounts = userAccounts;
	}

	public String getCardNum() {
		return this.cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	public String getCardExp() {
		return this.cardExp;
	}

	public void setCardExp(String cardExp) {
		this.cardExp = cardExp;
	}

	public Integer getCardCvv() {
		return this.cardCvv;
	}

	public void setCardCvv(Integer cardCvv) {
		this.cardCvv = cardCvv;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
