package neu.edu.entity;
// Generated Apr 28, 2017 7:49:59 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserAccounts generated by hbm2java
 */
public class UserAccounts implements java.io.Serializable {

	private Integer id;
	private Roles roles;
	private String username;
	private String password;
	private String name;
	private String email;
	private String phone;
	private Set<UserPaymentInfo> userPaymentInfos = new HashSet<UserPaymentInfo>(0);
	private Set<Projects> projectses = new HashSet<Projects>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);
	private Set<Comments> commentses = new HashSet<Comments>(0);

	public UserAccounts() {
	}

	public UserAccounts(Roles roles, String username, String password, String name, String email, String phone,
			Set<UserPaymentInfo> userPaymentInfos, Set<Projects> projectses, Set<Payment> payments,
			Set<Comments> commentses) {
		this.roles = roles;
		this.username = username;
		this.password = password;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.userPaymentInfos = userPaymentInfos;
		this.projectses = projectses;
		this.payments = payments;
		this.commentses = commentses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set<UserPaymentInfo> getUserPaymentInfos() {
		return this.userPaymentInfos;
	}

	public void setUserPaymentInfos(Set<UserPaymentInfo> userPaymentInfos) {
		this.userPaymentInfos = userPaymentInfos;
	}

	public Set<Projects> getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set<Projects> projectses) {
		this.projectses = projectses;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public Set<Comments> getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set<Comments> commentses) {
		this.commentses = commentses;
	}

}
